spring:
  datasource:
    url: jdbc:h2:mem:classStudentsDb
    driver-class-name: # org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: # org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

server:
  port: 8082

properties:
  security:
    jwt:
      base64-secret: ""
      token-validity-in-seconds: 0
      token-validity-in-seconds-for-remember-me: 0
